import { vazirmatn } from "./fonts";
import "./globals.css";
import { IngredientProvider } from "../store/ingredient-context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html style={{ direction: "rtl" }} lang="en">
      <body className={`${vazirmatn.className} antialiased`}>
        <IngredientProvider>{children}</IngredientProvider>
      </body>
    </html>
  );
}
